### ISSUE TITLE
[IMPROVE FE]  Change colour of leader name link

### ISSUE THREAD

**Issue by BobWritesCode** [BobWritesCode/squadup_frontend#71]
**What needs to be improved?**
Change the colour of the leader link in groups.

**Why does it need to be improved?**
Currently the colour stands out as a default style and does not fit in with the rest of the application.

**How should it be improved?**
Change to white, to better fit in

**Provide any evidence such as screenshots / code:**
![image](https://github.com/BobWritesCode/squadup_frontend/assets/104802720/27decec9-4f46-445c-9f8e-ab9536695e47)

**Comment by priddhesh** [comment]
Please assign me this task.

**Comment by BobWritesCode** [comment]
> Please assign me this task.

Thank you for your interest in helping, but this is a project for a course so I am unable to accept any outside assistance.
