### ISSUE TITLE
[BUG FE] Application acceptance issue

### ISSUE THREAD

**Issue by BobWritesCode** [BobWritesCode/squadup_frontend#72]
**Describe the bug** (A clear and concise description of what the bug is)
IF you accept an application but then close the modal, and reopen it. It will not reset the application. You will need to reload the page

**To Reproduce** (Steps to reproduce the behavior)
Have a group, have a request, click accept on request, close modal and reopen. you will not have the option to rechoose accept or reject, or have the form to complete. You will be required to refresh the page.

**Expected behaviour** (A clear and concise description of what you expected to happen)
Form should reset.

**Screenshots** (If applicable, add screenshots to help explain your problem)
![image](https://github.com/BobWritesCode/squadup_frontend/assets/104802720/6a26a29b-2bdf-45f8-ab05-99ae529349c8)

**Additional context** (Add any other context about the problem here)

**Comment by priddhesh** [comment]
Please assign me this task.I would like to work on this issue.
